sudo: required
language: node_js
node_js:
  - "4.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gconf-service
      - libasound2
      - libatk1.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libfreetype6
      - libgcc1
      - libgconf-2-4
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgtk2.0-0
      - libnspr4
      - libnss3
      - libpango1.0-0
      - libstdc++6
      - libx11-6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - ca-certificates
      - libappindicator1
      - libcurl3
      - lsb-base
      - xdg-utils
      - wget

cache:
  directories:
    - node_modules
    - $HOME/.jspm
    - $HOME/.tsd-cache

before_install:
  - export PATH=$PWD/node_modules/.bin:$PATH
  - export CXX=g++-4.8
  - sudo apt-get update
  - sudo apt-get install fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
  - sudo dpkg -i google-chrome-beta_current_amd64.deb
  - npm install -g npm@3.3.6
  - npm --version
  - $CXX --version

before_script:
  - jspm config registries.github.timeouts.lookup 60
  - jspm config registries.github.timeouts.build 120
  - jspm config registries.github.remote https://github.jspm.io
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm config registries.github.maxRepoSize 0
  - jspm config registries.github.handler jspm-github
  - jspm install
  - tsd install --overwrite

script:
  - ./scripts/build.sh
  - ./scripts/test_run.sh

