language: node_js
node_js:
  - "5.4.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-beta

cache:
  directories:
    - node_modules
    - protobuf
    - $HOME/.jspm
    - $HOME/.tsd-cache
    - $HOME/gopath

before_install:
  - export CXX=g++-4.8
  - env
  - npm install -g npm@3.5.3
  - $CXX --version

before_script:
  - source ./scripts/common_env.sh
  - source ./scripts/setup_env.sh
  - ./scripts/setup_go.sh
  - ./scripts/setup_typescript_test_packages.sh
  - ./scripts/protobuf_install.sh
  - ./scripts/dump_env.sh

script: ./scripts/test_runner.sh
