#!/usr/bin/env bash

set -e
set -o pipefail

output=$(git status --porcelain)

if [ -z "$output"  ]
then
  echo "Git is clean"
else
  >&2 echo -e "Git is not clean. The following files should have been committed:\n\n$output"
  exit 1
fi
