#!/usr/bin/env bash

set -e
shopt -s globstar
shopt -s extglob
set -o pipefail

ls src/**/*.{ts,tsx} | \
  grep -v src/lib.core.d.ts | \
  grep -v src/lib.dom.d.ts | \
  xargs tslint -c src/tslint.json
